services:
  - type: web
    name: my-n8n-web
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        sync: false
      - key: GENERIC_TIMEZONE
        value: UTC
      - key: N8N_METRICS
        value: true
